## numpy :: advanded

In [ ]:
import numpy as np
a1= (np.random.random((4,4))*10).astype(int)
a1

array([[2, 2, 1, 6],
       [7, 3, 1, 8],
       [4, 7, 9, 9],
       [8, 0, 3, 1]])

In [24]:
# Fancy indexing

# 1 ,3,4 row   (when there is no pattern in indexing)
a1[[0,2,3]]

# 1 ,3 ,4 col
a1[:,[0,2,3]]


array([[2, 1, 6],
       [7, 1, 8],
       [4, 9, 9],
       [8, 3, 1]])

### 
BOOLEAN INDEXING

In [ ]:
# boolean indexing (applying conditions!)

a2 =np.random.randint(1,100,24).reshape(6,4)

a2
a2>50

array([[95, 64, 40, 46],
       [ 2, 35, 74,  3],
       [ 7, 25, 74, 93],
       [61, 65, 10, 30],
       [85, 34,  4, 65],
       [78, 52, 96, 58]], dtype=int32)

In [42]:
# find all numbers greater than 50
a2[a2>50]
a2[a2%2==0] ## check even 

# find both greatr than 50 and even
a2[(a2>50) & (a2%2==0) ]

array([64, 74, 74, 78, 52, 96, 58], dtype=int32)