## Numpy

In [1]:
import numpy as np

In [25]:
a = np.array([1,2,3,4,5])
print(a)

array([['1', '2', '3'],
       ['4', '5', 'Arjun']], dtype='<U21')

In [16]:
# dtype
np.array([1,2,3,4], dtype=float)
np.array([1,2,3,4], dtype=str)
np.array([1,0,3,4], dtype=bool)
np.array([1,0,3,4], dtype=complex)

array([1.+0.j, 0.+0.j, 3.+0.j, 4.+0.j])

In [61]:
# arange
np.arange(1,11)
np.arange(1,11,2)

# reshape
np.arange(1,11).reshape(5,2)

# np.ones
np.ones((2,5) , dtype=int) 
# np.zeroes
np.zeros([2,3])

# np.random
np.random.random((2,5))


array([[0.47533499, 0.49901763, 0.44368797, 0.57383468, 0.94474852],
       [0.82038579, 0.45006087, 0.33294063, 0.53061547, 0.16938658]])

In [ ]:
'''np.linspace  (linear space)  like if we want some number of
 points b/w a range, this will generate those no. of point at equal distance b/w the range'''
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [65]:
# identity matrix
np.identity(3) # np.eye()

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes :


In [94]:
a1 = np.arange(10)
a2= np.arange(12,dtype=float).reshape(3,4)
a3 = np.arange(8,dtype=int).reshape(2,2,2)
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# ndim
a3.ndim


# shape
a1.shape
a2.shape
a3.shape

# size
a2.size

# itemsize  (tells the size of each item in bytes)
a3.itemsize
a = np.array(["a","b"])
a.itemsize

# dtype
a3.dtype


dtype('int64')

In [109]:
# changing datatype
a3.dtype
# lets say we are storing ag e, we know that we dont need to store age int64 format , to optimize memory we can even store it in int32
a3.astype(np.int32)




array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)