## Numpy Tricks:



In [ ]:
import numpy as np 
a= np.random.randint(10,50,12)
np.sort(a)

In [ ]:
b= np.random.randint(10,50,12).reshape(3,4)
# np.sort(b,axis=1)
np.sort(a)[::-1] # reverse sorting.
b


In [ ]:
# append
np.append(b,np.random.randint(1,10,4).reshape(1,4),axis=0)# dimensions should match 


In [ ]:
# concatenate   (follows broad casting wale dimention rules )
a = np.arange(6).reshape(3,2)
b = np.arange(3).reshape(3,1)
np.concatenate((a,b), axis=1)

In [61]:
# unique
a=np.array([1,1,2,2,3,3,4,0,0,0,5,6,6,6,7,7,1])
np.unique(a)

array([0, 1, 2, 3, 4, 5, 6, 7])

In [ ]:
# expand_dims  (convers 1d-> 2d   , 2d->3d   so this expands dimensions)
np.expand_dims(a,axis=1)

In [77]:
# np.where    -> returns the indices of the elements for which a given condition satifies
np.where(a>2)
a=np.random.randint(10,100,10).reshape(5,2)
a

array([[91, 12],
       [46, 98],
       [68, 12],
       [32, 54],
       [24, 59]], dtype=int32)

In [66]:
## replace all elements >50 with 0
np.where(a>50,0,a)


array([ 0,  0,  0,  0, 10,  0,  0,  0, 47,  0], dtype=int32)

In [80]:
# argmax (returns the index of the max element along a particular axis)
np.argmax(a ,axis=1)

array([0, 1, 0, 1, 1])

In [81]:
np.argmin(a)

np.int64(1)

In [88]:
# cumsum cumilative sum
a.shape
np.cumsum(a,axis=0)
np.cumprod(a,axis=0)



array([[       91,        12],
       [     4186,      1176],
       [   284648,     14112],
       [  9108736,    762048],
       [218609664,  44960832]])

In [100]:
 # percentile 
a=np.random.randint(10,100,10)
print(a)
print(np.median(a))
np.percentile(a,50)

[67 88 47 20 90 44 81 59 42 78]
63.0


np.float64(63.0)

In [102]:
np.histogram(a,bins=[0,20,40,60,80,100])

(array([0, 1, 4, 2, 3]), array([  0,  20,  40,  60,  80, 100]))

In [109]:
salary = np.array([2000,20003,10000,40005,66660,50000])
experience = np.array([5,4,3,2,1,0])
np.corrcoef(salary,experience)


array([[ 1.        , -0.87790475],
       [-0.87790475,  1.        ]])

In [ ]:
print(a)
np.isin(a,[2,3,4,5,67,20,78,1,0,9,45]) # a is searched in the list

[67 88 47 20 90 44 81 59 42 78]


array([ True, False, False,  True, False, False, False, False, False,
        True])

In [ ]:
# np.put to change multiple elements on certain indexes (makes permanent changes)
np.put(a,[0,2],[88,88])


In [ ]:
np.delete(a,[0,1,2])


array([88, 88, 88, 20, 90, 44, 81, 59, 42, 78], dtype=int32)

In [ ]:
# functions on sets 
a = np.array([1,2,3,4,5])
b = np.array([3,4,5,6,7])
np.union1d(a,b)
np.intersect1d(a,b)
np.setdiff1d(a,b)
np.setdiff1d(b,a)
np.setxor1d(a,b) ## removes the common part 


array([1, 2, 6, 7])

In [129]:
np.isin(a,[4,5])
a=np.random.randint(10,100,10)
a

array([37, 44, 55, 34, 40, 80, 20, 61, 40, 27], dtype=int32)

In [131]:
#  np.clip    (any elemenet below 30 becomes 30 and above 60 becomes 60)
np.clip(a,a_max=60,a_min=30)

array([37, 44, 55, 34, 40, 60, 30, 60, 40, 30], dtype=int32)